### ISSUE TITLE
#![no-std] support

### ISSUE THREAD

**Issue by martin2250** [YoloDev/hass-rs#46]
Hi Aleksander,

I found this repository working on a recent project of mine, connecting microcontrollers to Home Assistant with MQTT. Specifically I'm using the network stack from `embassy` and `rust-mqtt` (both with async support).

Right now, none of the crates here build in a no_std environment. Is that something you'd be interested in as well? I wouldn't mind putting in some work for the `mqtt-proto` crate as that's the most useful to me right now.

Cheers,
Martin

**Comment by Alxandr** [comment]
That's definitely interesting. The question is to what extent it can be done. But the lower level crates with the protos are trying to be alloc free, so I wouldn't be surpriced if it was doable. Does serde support `no_std` though?

**Comment by martin2250** [comment]
[Yes](https://github.com/serde-rs/serde/blob/master/serde/src/lib.rs#L98).

Alright, I'll see if I can get it to compile in the next few days

**Comment by martin2250** [comment]
So I tried that today, but I no longer think messing around with that is a good idea.
The main problem is `#[entity_document]`. I tried wrapping it in a `cfg` and otherwise just replacing it with `derive(Serialize)` like this:
```rust
#[cfg_attr(feature = "std", entity_document)]
#[cfg_attr(not(feature = "std"), derive(Serialize))]
pub struct BinarySensor<'a> {
```
but this gets rid of a lot of other types / implementations, so you'd have to put half of that crate behind `#[cfg]`s or remove a lot of functionality.

I think for my purposes, I'll just copy over the bare structs.

Cheers!

**Comment by Alxandr** [comment]
Be adviced that "the bare structs" doesn't tell the full story. `entity_document` adds a lot of fields to the struct.

**Comment by martin2250** [comment]
Good idea! I'll give it another shot when I'm done with the low level parts of my project, although the second proposal seems more sound overall.

**Comment by Alxandr** [comment]
Yes. The issue is whether or not it's doable ergonomically. I'm not entirely sure yet.
